# Service structure is used to select a current heading and potentially a
# position offset that changes the tf tree between the fcu and base_link
#
# The primary use case is for geolocation

# Note that the following are giving w.r.t the ENU inertial frame (east is 0 degrees)

float32 heading_enu             # degrees
geometry_msgs/Point offset_enu  # meters

---